# Generated by Django 3.2 on 2021-04-27 20:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=40)),
                ('author_post', models.CharField(max_length=40)),
                ('dated_on', models.DateField(default=datetime.date.today)),
                ('image', models.FileField(blank=True, null=True, upload_to='article/')),
            ],
        ),
        migrations.CreateModel(
            name='gallery_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('type_image', models.FileField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('news_image', models.FileField(upload_to='news/')),
                ('news_file', models.FileField(blank=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dated_on', models.DateField(default=datetime.date.today)),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gallery_type')),
            ],
        ),
    ]
